// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn1nAg9Epxtpk-TFK7DyvYfw1O-wSrAV8',
    appId: '1:1092609896535:web:686bb64e4b8596e50e7312',
    messagingSenderId: '1092609896535',
    projectId: 'spotify9999',
    authDomain: 'spotify9999.firebaseapp.com',
    storageBucket: 'spotify9999.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1pwl6MHmtadugWRaNo42FxtHldsUOotQ',
    appId: '1:1092609896535:android:31072ee02ef2e4220e7312',
    messagingSenderId: '1092609896535',
    projectId: 'spotify9999',
    storageBucket: 'spotify9999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUmv-k8p7uB9Vmbsb_4lLLKXBmBIPbQU8',
    appId: '1:1092609896535:ios:dbef6463ccc815860e7312',
    messagingSenderId: '1092609896535',
    projectId: 'spotify9999',
    storageBucket: 'spotify9999.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUmv-k8p7uB9Vmbsb_4lLLKXBmBIPbQU8',
    appId: '1:1092609896535:ios:dbef6463ccc815860e7312',
    messagingSenderId: '1092609896535',
    projectId: 'spotify9999',
    storageBucket: 'spotify9999.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn1nAg9Epxtpk-TFK7DyvYfw1O-wSrAV8',
    appId: '1:1092609896535:web:eea61dceecc7e15e0e7312',
    messagingSenderId: '1092609896535',
    projectId: 'spotify9999',
    authDomain: 'spotify9999.firebaseapp.com',
    storageBucket: 'spotify9999.firebasestorage.app',
  );
}
