// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXD1Fzta21K44iLF1aqchcuOZjizMTVv8',
    appId: '1:163738235739:web:bd9eccb2011afce672207e',
    messagingSenderId: '163738235739',
    projectId: 'spotify-clone-2e4e2',
    authDomain: 'spotify-clone-2e4e2.firebaseapp.com',
    storageBucket: 'spotify-clone-2e4e2.firebasestorage.app',
    measurementId: 'G-7LQZMDDRL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBL0Xsuepo9qehgGZ1QDCyBdIAR00ml3Y',
    appId: '1:163738235739:android:b8ffac678e958af872207e',
    messagingSenderId: '163738235739',
    projectId: 'spotify-clone-2e4e2',
    storageBucket: 'spotify-clone-2e4e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_4LOCVVZiKymO_AI3hmxrfNp9aPFYJWY',
    appId: '1:163738235739:ios:a078b1e89d9ed8c872207e',
    messagingSenderId: '163738235739',
    projectId: 'spotify-clone-2e4e2',
    storageBucket: 'spotify-clone-2e4e2.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_4LOCVVZiKymO_AI3hmxrfNp9aPFYJWY',
    appId: '1:163738235739:ios:a078b1e89d9ed8c872207e',
    messagingSenderId: '163738235739',
    projectId: 'spotify-clone-2e4e2',
    storageBucket: 'spotify-clone-2e4e2.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXD1Fzta21K44iLF1aqchcuOZjizMTVv8',
    appId: '1:163738235739:web:a87f870888f6168b72207e',
    messagingSenderId: '163738235739',
    projectId: 'spotify-clone-2e4e2',
    authDomain: 'spotify-clone-2e4e2.firebaseapp.com',
    storageBucket: 'spotify-clone-2e4e2.firebasestorage.app',
    measurementId: 'G-1B7TK8XNQD',
  );

}